import React, {useEffect, useRef, useState, lazy, Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import data from './data.json';
import './style.css';
import './upgrade.css';
import FoldText from './components/FoldText';
import SpecularButton from './components/SpecularButton';
import Stack from './components/Stack';
import OptimizedImage from './components/OptimizedImage';
import imageManifest from './image-manifest.json';
const MotionLayer=lazy(()=>import('./components/MotionLayer'));
import './motion.css';

const imagePath = i => '/image/' + encodeURIComponent(i.file);
const heroCards = [data.items[14],data.items[6],data.items[4],data.items[1]].map((item,index)=><figure key={item.file}><OptimizedImage item={item} hero priority={index===3} draggable="false"/><figcaption><span>{item.title}</span><span>{String(index+1).padStart(2,'0')} / 04</span></figcaption></figure>);
const tags = [...new Set(data.items.flatMap(i => i.tags))];
function readStorage(key, fallback) {try {const value=JSON.parse(localStorage.getItem(key)); return value ?? fallback;} catch {return fallback;}}
function App(){
 const [saved,setSaved]=useState(()=>{const raw=readStorage('inspiration-saved',[]);const list=Array.isArray(raw)?raw:[];return data.items.filter(i=>list.includes(i.file)||(i.aliases||[]).some(a=>list.includes(a))).map(i=>i.file)});
 const [comments,setComments]=useState(()=>{const raw=readStorage('inspiration-comments-v1',{});return raw && typeof raw==='object' && !Array.isArray(raw)?raw:{}});
 const [query,setQuery]=useState(''),[tag,setTag]=useState(''),[source,setSource]=useState(''),[shape,setShape]=useState(''),[sort,setSort]=useState('default'),[tab,setTab]=useState('all');
 const [active,setActive]=useState(null),[status,setStatus]=useState(false),[toast,setToast]=useState(''),[draft,setDraft]=useState(''),[dimensions]=useState(imageManifest);
 const [galleryVisible,setGalleryVisible]=useState(false),[motionReady,setMotionReady]=useState(false);
 const galleryRef=useRef(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setGalleryVisible(true);observer.disconnect()}},{rootMargin:'100px'});observer.observe(galleryRef.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{const activate=()=>setMotionReady(true);window.addEventListener('pointermove',activate,{once:true});return()=>window.removeEventListener('pointermove',activate)},[]);
 const detail=useRef(null),statusDialog=useRef(null),search=useRef(null),timer=useRef(null);
 const notify=text=>{setToast(text);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),2600)};
 const persist=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{notify('浏览器存储不可用，本次修改仅在当前页面保留')}};
 const toggleSave=file=>{const next=saved.includes(file)?saved.filter(x=>x!==file):[...saved,file];setSaved(next);persist('inspiration-saved',next)};
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 useEffect(()=>{if(active){setDraft('');detail.current.showModal()}else if(detail.current?.open)detail.current.close();document.body.style.overflow=active||status?'hidden':'';return()=>{document.body.style.overflow=''}},[active,status]);
 useEffect(()=>{if(status)statusDialog.current.showModal();else statusDialog.current?.close()},[status]);
 useEffect(()=>{const onKey=e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!active&&!status){e.preventDefault();document.getElementById('library').scrollIntoView();search.current.focus({preventScroll:true})}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[active,status]);
 const reset=()=>{setQuery('');setTag('');setSource('');setShape('');setSort('default');setTab('all')};
 const browse=(next='all')=>{setTab(next);document.getElementById('library').scrollIntoView({behavior:'smooth'})};
 let items=data.items.filter(i=>(!tag||i.tags.includes(tag))&&(!source||i.source===source)&&(!shape||(dimensions[i.file]?.shape||i.shape)===shape)&&(tab==='all'||saved.includes(i.file))&&query.trim().toLowerCase().split(/\s+/).every(q=>[i.title,i.author,i.file,i.source,...i.tags,...(i.aliases||[]),...(i.duplicateRecords||[]).flatMap(r=>[r.title,r.author,r.source])].join(' ').toLowerCase().includes(q)));
 if(sort==='new')items.sort((a,b)=>b.file.localeCompare(a.file));if(sort==='likes')items.sort((a,b)=>(Number(b.likes)||0)-(Number(a.likes)||0));
 const closeBackdrop=(e,close)=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}};
 const activeComments=active&&Array.isArray(comments[active.file])?comments[active.file]:[];
 const submitComment=e=>{e.preventDefault();if(!draft.trim())return;const next={...comments,[active.file]:[...activeComments,{id:crypto.randomUUID(),text:draft.trim(),date:new Date().toISOString()}]};setComments(next);persist('inspiration-comments-v1',next);setDraft('');notify('评论已保存')};
 return <>
 <header className="site-header"><div className="nav-inner"><a className="brand" href="#home"><span className="brand-icon">✳</span>素材灵感库<span className="beta">个人灵感空间</span></a><nav aria-label="主导航"><a href="#home">首页</a><button onClick={()=>browse()}>探索灵感</button><button onClick={()=>browse('saved')}>我的收藏 <span>{saved.length.toString().padStart(2,'0')}</span></button></nav><div className="profile"><span className="avatar">灵</span><span>灵感收藏家<small>今天也有新的灵感</small></span></div></div></header>
 <section className="fullscreen-hero" id="home"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span/> YOUR DAILY DOSE OF INSPIRATION</div><h1><FoldText text="让好灵感，" fontSize="inherit" fontWeight={500} color="#38382f" duration={.85} stagger={.07} trigger="mount"/><br/><FoldText text="随时有迹可循" fontSize="inherit" fontWeight={500} color="#b96b49" hinge="bottom" duration={1} stagger={.08} trigger="mount"/></h1><p>收集喜欢的画面，连接下一次创作。</p><SpecularButton className="explore-button" radius={8} tint="#c96a45" tintOpacity={1} lineColor="#ffe8ad" baseColor="#b25a39" intensity={2.5} thickness={1.5} autoAnimate onClick={()=>browse()}>探索我的灵感库 <span>↗</span></SpecularButton><div className="hero-count"><strong>{data.items.length.toString().padStart(2,'0')}</strong><span>份灵感已收藏于此<br/>等待下一次创作</span><i>✳</i></div></div><div className="hero-visual"><div className="visual-ring"/><div className="hero-stack"><Stack cards={heroCards} randomRotation sensitivity={130} sendToBackOnClick mobileClickOnly animationConfig={{stiffness:220,damping:24}}/></div><span className="stack-hint">拖动或点击，翻阅灵感 ↗</span><span className="hero-spark" aria-hidden="true">✳</span><span className="handwritten">A little spark, a new idea.</span></div></div><div className="hero-bottom"><span>建筑 · 景观 · 空间 · 创意</span><button onClick={()=>browse()}>向下探索 <span>↓</span></button><span>YOUR PERSONAL INSPIRATION ARCHIVE</span></div></section>
 <main id="library"><div className="section-heading"><div><div className="eyebrow">THE INSPIRATION COLLECTION</div><h2>每一眼心动，都有迹可循<span>✳</span></h2></div><p>让收藏，成为创作的开始。</p></div><section className="controls" aria-label="搜索和筛选"><div className="search-row"><label className="search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索灵感、标题、作者或文件名…" aria-label="搜索素材"/>{query&&<button onClick={()=>{setQuery('');search.current.focus()}} aria-label="清空搜索">×</button>}<kbd>/</kbd></label><select aria-label="来源筛选" value={source} onChange={e=>setSource(e.target.value)}><option value="">全部来源</option>{[...new Set(data.items.map(i=>i.source))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="图片比例" value={shape} onChange={e=>setShape(e.target.value)}><option value="">全部比例</option><option value="landscape">横图</option><option value="portrait">竖图</option><option value="square">方图</option></select></div><div className="filter-row"><div className="tags">{['',...tags].map(t=><button key={t} className={t===tag?'active':''} aria-pressed={t===tag} onClick={()=>setTag(t)}>{t||'全部'}</button>)}</div><button className="text-button reset" onClick={reset}>重置筛选 ↺</button></div></section>
 <section className="library"><div className="library-bar"><div className="tabs"><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>全部灵感 <span>{data.items.length}</span></button><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>我的收藏 <span>{saved.length}</span></button></div><div className="list-options"><span aria-live="polite">显示 {items.length} 张素材</span><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">默认排序</option><option value="new">文件名倒序</option><option value="likes">点赞最多</option></select></div></div><div className="gallery" ref={galleryRef} style={!galleryVisible&&items.length?{minHeight:600}:undefined}>{galleryVisible&&items.map(i=><article className="card" key={i.file}><div className="picture"><button className="open" onClick={()=>setActive(i)} aria-label={'查看 '+i.title}><OptimizedImage item={i}/></button><button className="save" onClick={()=>toggleSave(i.file)} aria-label={'收藏 '+i.title} aria-pressed={saved.includes(i.file)}>{saved.includes(i.file)?'♥':'♡'}</button></div></article>)}</div>{!items.length?<div className="empty"><div>✧</div><h2>{tab==='saved'?'这里还没有符合条件的收藏':'还没有找到这份灵感'}</h2><p>试试其他关键词，或调整筛选条件。</p><button onClick={reset}>查看全部灵感</button></div>:<div className="end">一共 {items.length} 份灵感，等待下一次创作 <span>✳</span></div>}</section><footer><span>素材灵感库 <i>·</i> 留住灵感，自在创作</span><button className="text-button" onClick={()=>setStatus(true)}>素材匹配情况</button></footer></main>
 <dialog id="detail" ref={detail} onClose={()=>setActive(null)} onClick={e=>closeBackdrop(e,()=>setActive(null))} aria-label="素材详情"><button className="close" aria-label="关闭详情" onClick={()=>setActive(null)}>×</button>{active&&<div id="detail-content"><div className="detail-image"><OptimizedImage item={active} detail/></div><div className="detail-info"><span className="mini-tag">{active.tags.slice(0,3).join(' · ')}</span><h2>{active.title}</h2>{active.inferred&&<p>此名称与分类根据图片画面临时整理；原始标题和作者尚未匹配。</p>}{active.aiTags&&<section className="ai-dimensions"><h3>AI 标签</h3>{Object.entries(active.aiTags).map(([k,v])=><p key={k}><strong>{k}</strong>{v.join(' · ')||'未识别'}</p>)}</section>}<dl><dt>来源</dt><dd>{active.source}</dd><dt>作者</dt><dd>{active.author||'待补充'}</dd><dt>文件名</dt><dd>{active.file}</dd><dt>尺寸</dt><dd>{dimensions[active.file]?.width||'—'} × {dimensions[active.file]?.height||'—'}</dd><dt>点赞</dt><dd>{active.likes||'暂无记录'}</dd></dl><SpecularButton id="detail-save" size="sm" radius={7} tint="#c96a45" tintOpacity={1} lineColor="#ffe8ad" intensity={2.5} onClick={()=>toggleSave(active.file)}>{saved.includes(active.file)?'♥ 已收藏':'♡ 收藏这份灵感'}</SpecularButton><br/><a href={imagePath(active)} download={active.file}>下载原图 ↓</a>{/^https?:\/\//i.test(active.url)?<a className="origin-button" href={active.url} target="_blank" rel="noopener noreferrer">访问原址 ↗</a>:<button className="origin-button" disabled>暂未记录原址</button>}<section className="comments"><h3>灵感评论 <span>{activeComments.length}</span></h3><p className="local-note">记录此刻的想法 · 仅保存在当前浏览器</p><form onSubmit={submitComment}><textarea aria-label="评论内容" placeholder="这份灵感，让你想到了什么？" value={draft} maxLength={1000} onChange={e=>setDraft(e.target.value)}/><div className="comment-submit"><span>{draft.length} / 1000</span><SpecularButton disabled={!draft.trim()} type="submit" size="sm" radius={6} tint="#c96a45" tintOpacity={1} lineColor="#ffe8ad" intensity={2.5}>发布评论</SpecularButton></div></form><div className="comment-list">{activeComments.length?activeComments.map(c=><article key={c.id} className="comment"><div className="comment-top"><strong>灵感收藏家</strong><time>{new Date(c.date).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div><p>{c.text}</p><button className="text-button" aria-label={'删除评论 '+c.text} onClick={()=>{const next={...comments,[active.file]:activeComments.filter(x=>x.id!==c.id)};setComments(next);persist('inspiration-comments-v1',next)}}>删除</button></article>):<p className="no-comments">还没有评论，留下第一笔灵感吧。</p>}</div></section></div></div>}</dialog>
 <dialog id="status" ref={statusDialog} onClose={()=>setStatus(false)} onClick={e=>closeBackdrop(e,()=>setStatus(false))} aria-label="素材匹配情况"><button className="close" aria-label="关闭匹配情况" onClick={()=>setStatus(false)}>×</button><h2>素材匹配情况</h2><p>本地图片：{data.deduplication?.scanned??data.items.length} 张<br/>展示素材：{data.items.length} 张<br/>已匹配表格：{data.matched} 张<br/>未找到图片的记录：{data.missing.length} 条</p>{data.missing.length>0&&<ul>{data.missing.map(x=><li key={x}>{x}</li>)}</ul>}<p>素材来自当前灵感库快照。评论与收藏仅保存在当前浏览器。</p></dialog>{motionReady&&<Suspense fallback={null}><MotionLayer modalOpen={Boolean(active||status)}/></Suspense>}<div id="toast" className={toast?'visible':''} role="status">{toast}</div>
 </>
}
createRoot(document.getElementById('root')).render(<App/>);
